#+TITLE: Readme

* DNSimple Role
- Purpose of this role is to iterate over a hosts list in YAML, check for existing records, and in the case there is no record to create one in the supplied domain.
* Requirements
- Python Libraries:
  - dnsimple
  - dnspython
  - jmespath
* Role Variables
#+begin_src
dnsimple_user: '#This should reference: vaut.<user>.user'
dnsimple_key: '#This should reference: vaut.<key>.user'
dnsimple_domain: '#This is the DNSimple Domain to work under: https://dnsimple.com/a/<acct#>/domains'
dnsimple_sandbox: '#Set to true if this is a sandbox account, otherwise False'
dnsimple_account_id: '#Found under the correct domain you want to access, instead of a userID'
dnsimple_hosts_to_add: '#Dictionary describing hosts to add, see [[#-example-playbook-][Example Playbook]]'
vault:
  sandbox:
    user: "{{ vault_account1.vault_user }}"
    key: "{{ vault_account2.vault_key }}"

dnsimple_headers:
  Authorization: "Bearer {{ vault.sandbox.key }}"
  Accepts:  "application/json"
#+end_src
* Vault
- vault.yml content should contain your API keys and usernames, and referenced in your playbook variables as shown above for easy search via grep. Vault should looke like:
  #+begin_src
vault_account1 :
  vault_user: user@email.net
  vault_key: <api-key>

vault_account2:
  vault_user: user@email.net
  vault_key: <api-key>
  #+end_src
* Example Playbook
:PROPERTIES:
:CUSTOM_ID: -example-playbook-
:END:
#+begin_src yaml
---
- name: update DNSimple records
  hosts: localhost
  vars:
    dnsimple_user: "{{ vault.sandbox.user }}"
    dnsimple_key: "{{ vault.sandbox.key }}"
    dnsimple_domain: "sassyatemyclothes.com"
    dnsimple_sandbox: True
    dnsimple_account_id: 1691
    dnsimple_headers:
      Authorization: "Bearer {{ vault.sandbox.key }}"
      Accepts:  "application/json"

    dnsimple_hosts_to_add:
      - hostname: test-record-one
        record_type: A
        content: 127.0.0.1
      - hostname:  test-record-two
        record_type: A
        content: 127.0.0.2
      - hostname: test-record-three
        record_type: A
        content: 127.0.0.3

    vault:
      account1:
        user: "{{ vault_sandbox.vault_user }}"
        key: "{{ vault_sandbox.vault_key }}"
  roles:
    - { role: dnsimple }
...
#+end_src
* Tasks
** install_dependencies
- Installs python3 and pip3 (This should probably not be done via Ansible, and preconfigured)
- Pip installs dnsimple, dataclasses, dnspython
- TODO: I think it's best to create a virtualenv on remote host and source that for the installs.
** get_existing_hosts
- Primary role of this role is to add new hosts, not change/remove. This role takes the dictionary defined in play variables and checks against the current entries in DNSimpe. A new dictionary is created with an additional fact stating whether or not it exists:
  #+begin_src sh
ok: [127.0.0.1] => (item={'msg': 'already_in_dns', 'failed': False, 'changed': False, 'item': {'name': 'test-record-four.int.new', 'content': '111.111.4.5'}, 'ansible_loop_var': 'item'}) => {
    "msg": "already_in_dns"
}

TASK [dnsimple : DNSimple API> Add hosts from hostfile YML to DNSimple] ****************************************************************************************************************************************************************************************
skipping: [127.0.0.1] => (item={'msg': 'already_in_dns', 'failed': False, 'changed': False, 'item': {'name': 'test-record-one', 'content': '192.168.2.31'}, 'ansible_loop_var': 'item'})
  #+end_src

- This dictionary is passed to the next task:
** add_hosts_dnsimple
- Iterates over the newly created dictionary and adds records if they were not found in the previous task ( get_existing_hosts ). This looks like:
  #+begin_src sh
    - "{{ dnsimple_hosts_list_with_existing_records.results }}"
  when: item.msg != "already_in_dns"
  #+end_src
* DONE Add per host record type: cname, a, mx, txt, etc
* TODOs
- Add a "change" option that will not only add but make updates to hosts
- Add a "decom" option so that hosts no longer in use can be removed
- Tie in with Device42 instead of manual creation of host dictionaries
